Add one-to-many join bidirectional between branch and chain
ithsjavagroupd/project pull request #80
Opened 2023-03-28 12:47 UTC by RehasLiamsi

2023-03-31 11:20 UTC, RehasLiamsi commented
Linked with #36 #37 #70

2023-03-31 11:21 UTC, RehasLiamsi commented
@figgge can you please take a look at the failing tests?

2023-03-31 13:09 UTC, Lugn1 commented on src/main/java/com/example/springbootproject/controller/ChainController.java
> +    @DeleteMapping("{chainId}/stores/{storeId}")
```suggestion
    @DeleteMapping("/{chainId}/stores/{storeId}")
```

2023-03-31 13:09 UTC, figgge commented on src/main/java/com/example/springbootproject/controller/ChainController.java
> +    }
```suggestion
   
```

2023-03-31 13:11 UTC, figgge commented on src/main/java/com/example/springbootproject/controller/StoreController.java
> +    }
```suggestion
  ```
We should remove this unused method.

2023-03-31 13:15 UTC, Lugn1 requested changes

2023-03-31 13:15 UTC, Lugn1 commented on src/main/java/com/example/springbootproject/controller/ChainController.java
> +    @DeleteMapping("{chainId}/stores/{storeId}")
```suggestion
    @DeleteMapping("/{chainId}/stores/{storeId}")
```

We need the forward slash before {chainId)

2023-03-31 13:15 UTC, Lugn1 commented on src/main/java/com/example/springbootproject/controller/ChainController.java
> +    @DeleteMapping("{chainId}/stores/{storeId}")
```suggestion
    @DeleteMapping("/{chainId}/stores/{storeId}")
```

2023-04-02 10:22 UTC, RehasLiamsi commented on src/main/java/com/example/springbootproject/controller/StoreController.java
> +    }
Hi, I added this method to be able to add chain to an existing store through the store database as well. That is why I put this method in store. If you think this is unnecessary and it should suffice with just being able to add stores to chains through the chain database, I can delete this method.

2023-04-03 11:30 UTC, figgge approved these changes

2023-04-03 12:14 UTC, Lugn1 approved these changes

2023-04-03 12:14 UTC, merged